# Generated by Django 5.0.7 on 2025-10-09 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('airport_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='slots.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='slots.city')),
            ],
            options={
                'unique_together': {('from_city', 'to_city')},
            },
        ),
        migrations.CreateModel(
            name='BlockTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField()),
                ('city_pair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block_time', to='slots.citypair')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.TimeField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='slots.airline')),
                ('city_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='slots.citypair')),
            ],
        ),
    ]
